# Generated by Django 3.2.9 on 2022-05-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.TextField(max_length=30)),
                ('Phonenumber', models.IntegerField()),
            ],
        ),
    ]
