# Generated by Django 3.2.9 on 2022-06-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0003_auto_20220603_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='makeorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('PhoneNumber', models.IntegerField()),
                ('Emailaddress', models.TextField()),
                ('Doorno', models.TextField()),
                ('Streetname', models.TextField()),
                ('Cityname', models.TextField()),
                ('Productdetails', models.ImageField(upload_to='')),
            ],
        ),
    ]
