# Generated by Django 3.2.9 on 2022-06-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0004_makeorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='makeorders',
            new_name='makeorder',
        ),
    ]
