# Generated by Django 3.2.9 on 2022-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0006_rename_makeorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('Email', models.TextField()),
                ('Phonenumber', models.IntegerField()),
                ('Orderedon', models.DateField()),
                ('Deliveredon', models.DateField()),
            ],
        ),
    ]
